# Generated by Django 3.1 on 2020-08-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=90)),
                ('body', models.CharField(max_length=900)),
                ('parsed', models.CharField(max_length=90)),
                ('keys', models.CharField(max_length=1000)),
            ],
        ),
    ]
